### ISSUE TITLE
Proofread MLPipeline notebook

### ISSUE THREAD

**Issue by alevine5** [alevine5/MADS-Capstone#41]
A few notes:

- Check last sentence of conclusion
- maybe clean up some outputs (potentially limit the number of heat maps displayed and the number of lines shown in the "Differences" section?
- maybe split notebook in two - one for ML train/test and one for creating visualizations?
- check each cell to make sure there are comments or markdown explanation

Totally up to you though in terms of output and formatting decisions!

**Comment by sammybigbux** [comment]
Good notes! I'm gonna make a checklist here to keep track of my changes:

- [ ] Check last sentence
- [ ] Limit number of heatmaps
- [ ] Add glossary with hyperlinks of format [section title](#section-title) to make easier to format
- [ ] Check over comments + markdown explanation
